### ISSUE TITLE
Stof Doctrine Extension example

### ISSUE THREAD

**Issue by Unamemma** [sadikoff/i18n-form-bundle#5]
Hi !

I can't figure how it works with stof doctrine extension, can i have an example ?

Thanks in advance

**Comment by NicolasDW** [comment]
Hi !

I can't figure how it works with stof doctrine extension, can i have an example ?

Thanks in advance

**Comment by sadikoff** [comment]
Sorry for sooo late answer the bundle was abandoned for a while, and finally it's back to life and refactoring!
